# Generated by Django 3.0.5 on 2020-04-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddam_w_dobre_rece', '0003_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='oddam_w_dobre_rece.Category'),
        ),
    ]
